### PR TITLE
98 responsiveness fix

### PR DESCRIPTION
**Pull request by activate-glacier-instinct**
Yoooooo

Summary:
- A ton of responsiveness features
- Biggest thing was abstracting the card and vstack into separate components
- Those abstractions let me really dial in the responsiveness and tweak it to an inch of it's life
- On mobile I added an inner scroll on the cards. Not sure about it, but it looks ok

Unfortunately I couldn't test all of the views because I didn't have token etc.

Get ready for screenshot overload! 

# Trove 

Trove views (ticked were tested): 
* [x] ACTIVE
* [x] ADJUSTING
* [x] CLOSING
* [ ] OPENING
* [ ] LIQUIDATED
* [ ] REDEEMED
* [ ] NONE

## Active

Desktop 
Screenshot from 2022-03-24 00-49-42

Mobile
Screenshot from 2022-03-24 00-50-09

## ADJUSTING

Desktop
Screenshot from 2022-03-24 00-49-53

Mobile
Screenshot from 2022-03-24 00-50-29

## Closing

Desktop
Screenshot from 2022-03-24 00-50-52

Mobile
Screenshot from 2022-03-24 00-51-05

# Stability

Stability views (ticked were tested): 
* [ ] NONE
* [ ] DEPOSITING
* [x] ADJUSTING
* [x] ACTIVE

## ACTIVE

Desktop
Screenshot from 2022-03-24 00-59-33

Mobile
Screenshot from 2022-03-24 00-59-44

## ADJUSTING

Desktop 
Screenshot from 2022-03-24 01-02-21

Mobile
Screenshot from 2022-03-24 01-02-37

# Stake 

Stake views (ticked were tested): 
* [ ] ACTIVE
* [x] ADJUSTING
* [x] NONE

## NONE 

Desktop
Screenshot from 2022-03-24 01-04-46

Mobile
Screenshot from 2022-03-24 01-05-02

## ADJUSTING

Desktop
Screenshot from 2022-03-24 01-06-24

Mobile
Screenshot from 2022-03-24 01-06-35

### CODE REVIEW

**Comment by activate-glacier-instinct** [comment]
Newly Tested pages

# Trove 

Trove views (ticked were tested): 
* [x] ACTIVE
* [x] ADJUSTING
* [x] CLOSING
* [x] OPENING
* [ ] LIQUIDATED
* [ ] REDEEMED
* [X] NONE

## None

Desktop
Screenshot from 2022-03-25 01-44-14


Mobile
Screenshot from 2022-03-25 01-44-02

## Opening

Desktop
Screenshot from 2022-03-25 01-49-02

Mobile
Screenshot from 2022-03-25 01-48-43

# Stability

Stability views (ticked were tested): 
* [x] NONE
* [x] DEPOSITING
* [x] ADJUSTING
* [x] ACTIVE

## NONE

Desktop
Screenshot from 2022-03-25 01-59-27

Mobile
Screenshot from 2022-03-25 01-59-41

## DEPOSITING

Desktop
Screenshot from 2022-03-25 02-01-14

Mobile
Screenshot from 2022-03-25 02-01-26


# Stake 

Stake views (ticked were tested): 
* [x] ACTIVE
* [x] ADJUSTING
* [x] NONE

## ACTIVE 

Desktop
Screenshot from 2022-03-25 02-07-30

Mobile
Screenshot from 2022-03-25 02-07-54

**Comment by activate-glacier-instinct** [comment]
Implemented the new responsive card on these pages too, but couldn't test.
* LIQUIDATED
* REDEEMED

Liquidated, not sure how we would test.
Redeemed, was missing 9 LUSD and that blocked me from liquidation.

**Comment by activate-glacier-instinct** [comment]
Full list of view for testing, maybe we can get help with this @geositta 

# Refactored pages 

Trove: 
* [ ] ACTIVE
* [ ] ADJUSTING
* [ ] CLOSING
* [ ] OPENING
* [ ] LIQUIDATED
* [ ] REDEEMED
* [ ] NONE

Stability:
* [ ] NONE
* [ ] DEPOSITING
* [ ] ADJUSTING
* [ ] ACTIVE

Stake:
* [ ] ACTIVE
* [ ] ADJUSTING
* [ ] NONE

**Review by geositta — APPROVED** [review]
This card abstraction is a big improvement, thank you! There is still some tweaking that I think is needed in terms of desktop. The adjust/editing of an open trove has overflow scroll when I would prefer the container to grow to fit the contents.
Screen Shot 2022-03-25 at 9 18 10 AM

**Pull request merged**
